package br.com.gabrielly;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

public class Calculadora_Jframe extends javax.swing.JFrame {

    double numero1;
    double numero2;
    double resultado;
    boolean nuM = true;
    String operacao;

    //new javax.swing.ImageIcon(getClass().getResource("raizQuadrada.jpg"))
    /**
     * Creates new form Calculadora_Jframe
     */
    public Calculadora_Jframe() {
        initComponents();
        URL url = this.getClass().getResource("/br/com/gabrielly/resource/calcular.png"); 
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url); this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        Subtracao = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        Multi = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        Div = new javax.swing.JButton();
        botao0 = new javax.swing.JButton();
        Adicao = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        botaoCE = new javax.swing.JButton();
        botaoP = new javax.swing.JButton();
        Resultado = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        botaoPorce = new javax.swing.JButton();
        botaoRaiz = new javax.swing.JButton();
        botaoTangente = new javax.swing.JButton();
        botaoSeno = new javax.swing.JButton();
        botaoCosseno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calc Gabi");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        botao8.setText("8");
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });

        botao9.setText("9");
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });

        Subtracao.setText("-");
        Subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtracaoActionPerformed(evt);
            }
        });

        botao5.setText("5");
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });

        botao6.setText("6");
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });

        Multi.setText("x");
        Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiActionPerformed(evt);
            }
        });

        botao2.setText("2");
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao3.setText("3");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        Div.setText("/");
        Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivActionPerformed(evt);
            }
        });

        botao0.setText("0");
        botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao0ActionPerformed(evt);
            }
        });

        Adicao.setText("+");
        Adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicaoActionPerformed(evt);
            }
        });

        botao7.setText("7");
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });

        botao4.setText("4");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        botao1.setText("1");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botaoCE.setText("CE");
        botaoCE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCEActionPerformed(evt);
            }
        });

        botaoP.setText(".");
        botaoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPActionPerformed(evt);
            }
        });

        Resultado.setText("=");
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });

        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblResult.setFocusable(false);
        lblResult.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        botaoPorce.setText("%");
        botaoPorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPorceActionPerformed(evt);
            }
        });

        botaoRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielly/resource/raiz-quadrada.png"))); // NOI18N
        botaoRaiz.setIconTextGap(1);
        botaoRaiz.setMaximumSize(new java.awt.Dimension(938, 526));
        botaoRaiz.setMinimumSize(new java.awt.Dimension(938, 526));
        botaoRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRaizActionPerformed(evt);
            }
        });

        botaoTangente.setText("Tan");
        botaoTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTangenteActionPerformed(evt);
            }
        });

        botaoSeno.setText("Sin");
        botaoSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSenoActionPerformed(evt);
            }
        });

        botaoCosseno.setText("Cos");
        botaoCosseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCossenoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botao4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(botao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botaoPorce, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Div, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(botaoCosseno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botaoSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botaoTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCE, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Div, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoRaiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoPorce, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoCosseno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botao0, botao2, botao5, botao8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Adicao, botao3, botao6, botao9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Div, Multi, Resultado, Subtracao});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botao1, botao4, botao7, botaoP});

        botao8.getAccessibleContext().setAccessibleParent(botao8);
        botao9.getAccessibleContext().setAccessibleParent(botao9);
        Subtracao.getAccessibleContext().setAccessibleParent(Subtracao);
        botao5.getAccessibleContext().setAccessibleParent(botao5);
        botao6.getAccessibleContext().setAccessibleParent(botao6);
        Multi.getAccessibleContext().setAccessibleParent(Multi);
        botao2.getAccessibleContext().setAccessibleParent(botao2);
        botao3.getAccessibleContext().setAccessibleParent(botao3);
        Div.getAccessibleContext().setAccessibleParent(Div);
        botao0.getAccessibleContext().setAccessibleParent(botao0);
        Adicao.getAccessibleContext().setAccessibleParent(Adicao);
        botao7.getAccessibleContext().setAccessibleParent(botao7);
        botao4.getAccessibleContext().setAccessibleParent(botao4);
        botao1.getAccessibleContext().setAccessibleParent(botao1);
        botaoCE.getAccessibleContext().setAccessibleParent(botaoCE);
        botaoP.getAccessibleContext().setAccessibleParent(botaoP);
        Resultado.getAccessibleContext().setAccessibleParent(Resultado);
        botaoRaiz.getAccessibleContext().setAccessibleParent(botaoRaiz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao0ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(0)));
        } else {
            jTextField1.setText("0");
            nuM = true;
        }

    }//GEN-LAST:event_botao0ActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(1)));
        } else {
            jTextField1.setText("1");
            nuM = true;
        }
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(2)));
        } else {
            jTextField1.setText("2");
            nuM = true;
        }
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(3)));
        } else {
            jTextField1.setText("3");
            nuM = true;
    }//GEN-LAST:event_botao3ActionPerformed
    }
    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(4)));
        } else {
            jTextField1.setText("4");
            nuM = true;
    }//GEN-LAST:event_botao4ActionPerformed
    }
    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(5)));
        } else {
            jTextField1.setText("5");
            nuM = true;
    }//GEN-LAST:event_botao5ActionPerformed
    }
    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(6)));
        } else {
            jTextField1.setText("6");
            nuM = true;
        }
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(7)));
        } else {
            jTextField1.setText("7");
            nuM = true;
    }//GEN-LAST:event_botao7ActionPerformed
    }

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(8)));
        } else {
            jTextField1.setText("8");
            nuM = true;
    }//GEN-LAST:event_botao8ActionPerformed
    }

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        if (nuM) {
            jTextField1.setText(jTextField1.getText().concat(String.valueOf(9)));
        } else {
            jTextField1.setText("9");
            nuM = true;
    }//GEN-LAST:event_botao9ActionPerformed
    }
    private void AdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicaoActionPerformed
        operacao = "soma";
        numero1 = Double.parseDouble(jTextField1.getText());
        lblResult.setText(jTextField1.getText() + " + ");
        jTextField1.setText("");
    }//GEN-LAST:event_AdicaoActionPerformed


    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        numero2 = Double.parseDouble(jTextField1.getText());
        lblResult.setText(lblResult.getText() + jTextField1.getText() + " = ");
        switch (operacao) {
            case "soma":
                resultado = numero1 + numero2;
                break;
            case "subtracao":
                resultado = numero1 - numero2;
                break;
            case "div":
                resultado = numero1 / numero2;
                break;
            case "multi":
                resultado = numero1 * numero2;
                break;
            case "percentual":
                resultado = ((numero1 * numero2) / 100);
                break;
        }
        jTextField1.setText(String.valueOf(resultado));
        numero1 = resultado;
        nuM = false;

    }//GEN-LAST:event_ResultadoActionPerformed

    private void SubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtracaoActionPerformed
        operacao = "subtracao";
        numero1 = Double.parseDouble(jTextField1.getText());
        lblResult.setText(jTextField1.getText() + " - ");
        jTextField1.setText("");
    }//GEN-LAST:event_SubtracaoActionPerformed

    private void MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiActionPerformed
        operacao = "multi";
        numero1 = Double.parseDouble(jTextField1.getText());
        lblResult.setText(jTextField1.getText() + " x ");
        jTextField1.setText("");
    }//GEN-LAST:event_MultiActionPerformed

    private void DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivActionPerformed
        operacao = "div";
        numero1 = Double.parseDouble(jTextField1.getText());
        lblResult.setText(jTextField1.getText() + " / ");
        jTextField1.setText("");
    }//GEN-LAST:event_DivActionPerformed

    private void botaoCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCEActionPerformed
        numero1 = 0;
        jTextField1.setText(null);
        lblResult.setText(null);
    }//GEN-LAST:event_botaoCEActionPerformed

    private void botaoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPActionPerformed
        jTextField1.setText(jTextField1.getText().concat(String.valueOf(".")));
    }//GEN-LAST:event_botaoPActionPerformed

    private void botaoPorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPorceActionPerformed
        operacao = "percentual";
        numero1 = Double.parseDouble(jTextField1.getText());
        lblResult.setText(jTextField1.getText() + " % ");
        jTextField1.setText("");
    }//GEN-LAST:event_botaoPorceActionPerformed

    private void botaoRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRaizActionPerformed
        numero1 = Double.parseDouble(jTextField1.getText());
        resultado = Math.sqrt(numero1);
        lblResult.setText(jTextField1.getText() + " Rz ");
        jTextField1.setText(String.valueOf(resultado));
        numero1 = resultado;
        nuM = false;
    }//GEN-LAST:event_botaoRaizActionPerformed

    private void botaoTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTangenteActionPerformed
        numero1 = Double.parseDouble(jTextField1.getText());
        resultado = Math.tan(numero1);
        lblResult.setText(jTextField1.getText() + " Tan ");
        jTextField1.setText(String.valueOf(resultado));
        numero1 = resultado;
        nuM = false;
    }//GEN-LAST:event_botaoTangenteActionPerformed

    private void botaoSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSenoActionPerformed
        numero1 = Double.parseDouble(jTextField1.getText());
        resultado = Math.sin(numero1);
        lblResult.setText(jTextField1.getText() + " Sin ");
        jTextField1.setText(String.valueOf(resultado));
        numero1 = resultado;
        nuM = false;
    }//GEN-LAST:event_botaoSenoActionPerformed

    private void botaoCossenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCossenoActionPerformed
        operacao = "Cosseno";
        numero1 = Double.parseDouble(jTextField1.getText());
        resultado = Math.cos(numero1);
        lblResult.setText(jTextField1.getText() + " Cos ");
        jTextField1.setText(String.valueOf(resultado));
        numero1 = resultado;
        nuM = false;
    }//GEN-LAST:event_botaoCossenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_Jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicao;
    private javax.swing.JButton Div;
    private javax.swing.JButton Multi;
    private javax.swing.JButton Resultado;
    private javax.swing.JButton Subtracao;
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoCE;
    private javax.swing.JButton botaoCosseno;
    private javax.swing.JButton botaoP;
    private javax.swing.JButton botaoPorce;
    private javax.swing.JButton botaoRaiz;
    private javax.swing.JButton botaoSeno;
    private javax.swing.JButton botaoTangente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblResult;
    // End of variables declaration//GEN-END:variables
}
